services:
  mysql:
    image: mysql:8.0-debian
    platform: linux/amd64
    container_name: panel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panel
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - cdntip_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    platform: linux/amd64
    container_name: panel_redis
    restart: always
    networks:
      - cdntip_network
    volumes:
      - ./data/redis:/data

  panel:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: panel
    restart: always
    ports:
      - "8111:889"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - cdntip_network
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=panelProject.settings
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=panel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  cdntip_network:
    driver: bridge 